version: '3'
services:
  ccri:
    container_name: ccri
    build: ccri-fhirserver
    image: thorlogic/ccri-fhirserver:${CCRI_VERSION}
    depends_on:
      - ccrisql
    links:
      - ccrisql
    environment:
      - datasource.username=${MYSQL_FHIR_USER}
      - datasource.password=${MYSQL_FHIR_PASSWORD}
      - datasource.host=//ccrisql
      - datasource.driver=com.mysql.jdbc.Driver
      - datasource.path=3306/careconnect?autoReconnect=true
      - datasource.vendor=mysql
      - datasource.showSql=true
      - datasource.showDdl=true
      - datasource.cleardown.cron=0 19 21 * * *
      - datasource.dialect=org.hibernate.dialect.MySQL57Dialect
      - datasource.ui.serverBase=http://localhost/careconnect-ri/STU3
      - datasource.ui.server=http://194.189.27.194/careconnect-ri/STU3
    ports:
      - 8080:8080
    volumes:
      - tomcat-log-volume:/usr/local/tomcat/logs

  ccrisql:
    container_name: ccrisql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=careconnect
      - MYSQL_USER=${MYSQL_FHIR_USER}
      - MYSQL_PASSWORD=${MYSQL_FHIR_PASSWORD}
    ports:
      - 43306:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_bin --innodb_lock_wait_timeout=300 --transaction-isolation=READ-UNCOMMITTED
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  elk:
    build: elk
    image: thorlogic/ccri-elk:${CCRI_VERSION}
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"

  filebeat:
    build: filebeat
    image: thorlogic/ccri-filebeat:${CCRI_VERSION}
    volumes:
      - tomcat-log-volume:/var/log/tomcat:ro
    depends_on:
      - elk
    links:
      - elk

volumes:
  tomcat-log-volume:
